name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ssh -i "resume-kp.pem" ubuntu@ec2-3-7-46-33.ap-south-1.compute.amazonaws.com

      - name: Copy files to EC2
        run: |
          scp -o StrictHostKeyChecking=no -r . ec2-user@3.7.46.33:/home/ec2-user/your-app-directory

      - name: SSH into EC2 and deploy
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@3.7.46.33 << 'EOF'
          cd /home/ec2-user/your-app-directory
          npm install
          npm start
          EOF
